# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âœ'

format = """
$username\
$hostname\
$directory\
$git_branch\
$line_break\
$cmd_duration\
$status\
$sudo\
$character\
"""

right_format = """
$git_status\
$git_commit\
$git_metrics\
"""

[username]
style_user = 'green bold'
style_root = 'red bold'
format = '[\[](237)[$user]($style)[@](15)'
disabled = false
show_always = true

[hostname]
ssh_only = false
ssh_symbol = ' ï›¿ '
format = '[$hostname](bold #00afff)[$ssh_symbol](bold red)[\]](237)'
disabled = false

[directory]
format = '[\[](237)[$path](246)[\]](237)'
home_symbol = '~'
truncation_symbol = '../'
truncation_length = 4

[git_branch]
symbol = 'ï„¦ '
format = '[\[](237)[$symbol](71)[branch:](bright-white)[$branch](104)[\]](237) '

[line_break]
disabled = false

[cmd_duration]
show_milliseconds = true
format = '[\[](237)[$duration]($style)[\]](237)'
style = 'bold #5f87d7'
min_time = 2

[character] # The name of the module we are configuring is 'character'
success_symbol = '[\[](237)[>](bold 112)[\]](237)'
error_symbol = '[\[](237)[>](bold red)[\]](237)'
vimcmd_symbol = '[\[](237)[ï„‡](bold red)[\]](237)' 
disabled = false

[status]
style = 'bold red'
success_symbol = 'ïŒƒ'
symbol = 'ğŸ’£ '
not_executable_symbol =	'ğŸš«'
not_found_symbol = 'ğŸ”'
sigint_symbol =	'ğŸ§¨'
signal_symbol = 'ğŸ’€'
recognize_signal_code =	true
map_symbol = true
disabled = false
format = '[\[](237)[$symbol - [$status](white)](bold $style)[\]](237)'

[sudo]
style = 'bold green'
format = '[\[](237)[$symbol]($style)[\]](237)'
symbol = 'ğŸ”“'
disabled = false

[git_status]
modified = ' ï–­ \($count\)'
format = '([\[](237)[($untracked)($staged) ($modified)[:](bold bright-white)[$ahead_behind](bold green)](bold blue)[\]](237)) '
staged = '[+\($count\)](green) '
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[git_commit]
commit_hash_length = 7
tag_symbol = 'ğŸ”– '
style = "bold #875fff"
format = '[\[](237)[\($hash$tag\)]($style)[\]](237) '
