# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âœ'


format = """
$username\
$hostname\
$directory\
$git_branch\
$line_break\
$cmd_duration\
$status\
$sudo\
$character\
"""

right_format = """
$git_status\
$git_commit\
$git_metrics\
"""

[username]
format = '[\[](244)[$user]($style)[@](bold green)'
style_user = "bold cyan"
style_root = 'red'
disabled = false
show_always = true

[hostname]
ssh_only = false
ssh_symbol = ' ï›¿ '
format = '[$hostname](bold purple)[$ssh_symbol](red)[\]](244)'
disabled = false

[directory]
format = '[\[](244)[$path](bold green)[\]](244)'
home_symbol = '~'
truncation_symbol = '../'
truncation_length = 4

[git_branch]
symbol = 'ï„¦ '
format = '[\[](244)[$symbol](71)[branch:](bright-white)[$branch](104)[\]](244) '

[line_break]
disabled = false

[cmd_duration]
show_milliseconds = true
format = '[\[](244)[$duration]($style)[\]](244)'
style = 'bold yellow'
min_time = 2

[character] # The name of the module we are configuring is 'character'
success_symbol = '[\[](244)[>](bold green)[\]](244)'
error_symbol = '[\[](244)[>](bold red)[\]](244)'
vimcmd_symbol = '[\[](244)[ï„‡](bold red)[\]](244)' 
disabled = false

[status]
style = ' red'
success_symbol = 'ïŒƒ'
symbol = 'ğŸ’£ '
not_executable_symbol =	'ğŸš«'
not_found_symbol = 'ğŸ”'
sigint_symbol =	'ğŸ§¨'
signal_symbol = 'ğŸ’€'
recognize_signal_code =	true
map_symbol = true
disabled = false
format = '[\[](244)[$symbol - [$status](white)]( $style)[\]](244)'

[sudo]
style = ' green'
format = '[\[](244)[$symbol]($style)[\]](244)'
symbol = 'ğŸ”“'
disabled = false

[git_status]
modified = ' ï–­ \($count\)'
format = '([\[](244)[($untracked)($staged) ($modified)[:]( bright-white)[$ahead_behind]( green)]( blue)[\]](244)) '
staged = '[+\($count\)](green) '
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[git_commit]
commit_hash_length = 7
tag_symbol = 'ğŸ”– '
style = " #875fff"
format = '[\[](244)[\($hash$tag\)]($style)[\]](244) '

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
